name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set Version
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check Version
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            uomumeraltaf/datascience-notebook:lab-4.2.4-${{ steps.vars.outputs.sha_short }}