name: Build JupS3

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: NPM Install
        run: |
          npm install
          yarn set version stable
          corepack enable
          yarn config set -H enableImmutableInstalls false

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build jupyter

      - name: Build package
        run: |
          python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_DEPLOY_KEY }}